baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'iPad Demonstration'
disableKinds = [ "taxonomy", "term" ]
staticDir = "static"
relativeURLs = true
publishDir = "docs"
uglyURLs = false

[params]
    homePageFilename = ""
#    homePageFilename = "index.html" <-- CHANGE if using uglyURLs